### ISSUE TITLE
Err() method may be remove locks

### ISSUE THREAD

**Issue by dspasibenko** [LK4D4/joincontext#1]
Would not you consider to make a small improvement by removing unnecessary locks in Err() function?

**Comment by LK4D4** [comment]
@dspasibenko I don't think that locking is unnecessary there. It's definitely could be set in `cancel` in parallel with `Err()` call. Race detector will complain about that. Let me know if you have ideas how to avoid Locks there.

**Comment by dspasibenko** [comment]
@LK4D4 My bad. It seems the only an alternative way to avoid the lock is atomic.SetPointer() coupling it with unsafe.Pointer in the `cancel()`. You will save syscalls for the mutex, but performance benefits are still questionable.  

Anyway, good pattern for mixing context, will use it, thanks for the implementation!
