### ISSUE TITLE
Dynamically join contexts

### ISSUE THREAD

**Issue by sheerun** [LK4D4/joincontext#3]
Thank you for creating this!

Could you also support joining dynamic context? I don't know all context I want to join upfront.

At the end something like `joincontext.JoinDynamic(writerCtx, readerCtx)`  where `readerCtx` is generated dynamically.

**Comment by LK4D4** [comment]
@sheerun Thanks for kind words!
I'm not sure what dynamic context means.
Usually, in Go everything is mostly static :) So, you will create `readerCtx` somewhere anyway and there you'll call `joincontext.Join`.
Maybe I just don't get your use-case, will appreciate snippet if that's so.
Thanks!

**Comment by sheerun** [comment]
Imagine I schedule job to do in one request:

```
jobRequest := newJobRequest(request.Context())
```

Then any number of workers to work on this job (they register themselves, when they are available).
```
worker := newWorker(request.Context(), jobRequest)
```

Now I want to arrange things so that worker's context gets cancelled automatically when request context is cancelled. I don't know the number of workers and they can appear at any time.

---

Writing this makes me realize that I can just do `worker.Ctx = joincontext.Join(jobRequest.Ctx, request.Context())`, so never mind. I was thinking I need to cancel `request.Context()` itself and joincontext is always creating new context instead attaching once context to another. But on the second thought it's probably not possible as I can't cancel request.Context() because I don't create it and I'd need to use WithContext() to get cancelling function.

It doesn't need to make sense to you, Thanks again and sorry to bother :)
